### ISSUE TITLE
Better tables tracking issue

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/tghandbook#12]
Add better table integration with fuzzy search (eg. like in chemistry/drinks/foods) to the following pages:

- [ ] Ghetto chemistry
- [ ] Guide to Medicine
  - [ ] Organ table
  - [ ] Typical cases of death (minor)
- [ ] Guide to Traumas
- [ ] Guide to the Supermatter - Gas interactions
- [ ] Guide to robotics - Upgrades
- [ ] Guide to genetics
- [ ] Guide to Circuits
- [ ] Guide to Restaurant
- [ ] Guide to hydroponics
  - [ ] Traits
  - [ ] Chemicals
  - [ ] Plant reference chart
- [ ] Supply crates
- [ ] Guide to Combat
- [ ] Syndicate Items
- [ ] Blood Cult
- [ ] Abductor
- [ ] Heretic (limited)
- [ ] AI modules
- [ ] Hacking (maybe requires a custom implementation)
- [ ] Critters
- [ ] Mafia

**Comment by Hamcha** [comment]
Good examples on how to implement these: https://github.com/Hamcha/tghandbook/blob/master/src/scripts/pages/ghettochem.ts

Basically move any multi-col table that could work in two-columns to that.
