### ISSUE TITLE
Performance issues tracker

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/tghandbook#5]
from https://git.fromouter.space/Hamcha/tghandbook/issues/9

- [ ] Debounce search box interactions
- [ ] Regression in processing time for initial load time and tab switching in recent Chromium (at least v96)
- [ ] Regression in fuzzy search speed in Firefox (my hunch says Chemistry is at fault here)

**Comment by Hamcha** [comment]
Chromium regression only happens in my machine and I cannot profile it because it just crashes every chromium-based browser I have, dunno what to do about it…
